// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAB {
    
    public class PREFAB {
        public const string BUNDLENAME = "grayrun/prefab";
        public const string BLUEHERO = "bluehero";
        public const string BOTTLE2 = "bottle2";
        public const string GREENHERO = "greenhero";
        public const string REDHERO = "redhero";
        public const string UIHOMELAYER = "uihomelayer";
        public const string UIMAPLAYER = "uimaplayer";
        public const string YELLOWHERO = "yellowhero";
    }
}
